name: Container Scanning Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t xg/vuln-app:${{ github.sha }} .

      - name: 'Install Trivy'
        run: |
          echo "Installing Trivy"
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      
      - name: 'Run Trivy Scan'
        run: |
          echo "Scanning the Docker image with Trivy"
          trivy image --severity MEDIUM,HIGH,CRITICAL xg/vuln-app:${{ github.sha }}

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/dependency-results.sbom.json'
          retention-days: 20 # 90 is the default