name: Testing DevSecOps Pipeline

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  pull_request:
    branches:
      - master

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build a Docker image
        run: docker build -t xgrid/test-vulnerable-image .
        
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: xgrid/test-vulnerable-image
          args: --file=Dockerfile --severity-threshold=high