name: Container Scanning Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t xg/vuln-app:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'xg/vuln-app:${{ github.sha }}'
          severity: 'MEDIUM,CRITICAL,HIGH'
          exit-code: '1'
          format: 'table'
          output: 'trivy-results'

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/trivy-results'
          retention-days: 20 # 90 is the default