name: Testing DevSecOps Pipeline

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
